package programmers2_task;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import programmers2_task.handler.mkdirHandler;
import programmers2_task.handler.num1Handler;
import programmers2_task.handler.num2Handler;

public class App {
    public static void main(String[] args) throws Exception {
        mkdirHandler.mkdir();
        num1Handler.num1();
        num2Handler.num2();

    }
}
